### ISSUE TITLE
Move to rebar

### ISSUE THREAD

**Issue by xadhoom** [lehoff/chronos#6]
It will be great if chronos moves to rebar as build tool, since using erlang.mk has some issues when compiling mixed packages which uses the REBAR_DEPS_DIR env variable.

I'm not an erlang expert (just learing elixir now), otherwise will be more than happy to submit a PR for that.

(for reference: https://elixirforum.com/t/help-with-erlang-module-not-available-when-testing-in-travis/2338/10 )

**Comment by xadhoom** [comment]
I rewrote the entire library in Elixir, just to make it easier to include into my project.

I also used and adapted some of your descriptions, while giving all the references to this as the original project.

The library is here: https://github.com/xadhoom/etimer , if you have some comments on it, it will be more than welcome :)

**Comment by lehoff** [comment]
I have talked to Essen and there should not be any problems using erlang.mk with Elixir.
 
But if you have  set REBAR_DEPS_DIR=$TRAVIS_BUILD_DIR/deps the you also need to do DEPS_DIR=$TRAVIS_BUILD_DIR/deps - otherwise it barfs on you.

Forking is fine, but I don't think it does anything good for the community. Basic features such as chronos should be done in Erlang for now. Right now it is a little too painful to include Elixir libraries in Erlang.

**Comment by xadhoom** [comment]
well I rewrote it just for easier inclusion in elixir projects, not for using it the pure erlang ecosystem, which makes no sense at all.

**Comment by lehoff** [comment]
It should actually just work out of the box in Elixir. 
Could you provide me with a minimal example of where it fails?
Then I will try to make it work.

My point is that core functionality such as Chronos, if started in Erlang should stay in Erlang because it will benefit both Erlang and Elixir. 
Exceptions would be things that started in Elixir and grew, then the friction of calling them from Erlang would be worth it. Or things that are easier to do in Elixir, e.g., an inference rules engine or prime number generation would probably be easier to do in Elixir because you can choose to have mutable variables. The are more examples, but those where two that I ran into on the Erlang side once and now that we have Elixir I would not do them in Erlang anymore.

**Comment by xadhoom** [comment]
well, I'm really lost now.

I spent the last 3 hours trying to reproduce the issue here https://travis-ci.org/xadhoom/detectino-core/builds/174918404 but without any luck.

at this point, I really do not know what I was doing....

**Comment by xadhoom** [comment]
I notice another thing (that was already there and is still there): I have to add the :gproc dep in my mix.exs otherwise is not found during execution.

Also I need to start the gproc application from my stack, shouldn't it be started by :chronos app?

**Comment by xadhoom** [comment]
Ok, I have a sample scenario where is happens. But only on travis :/

Travis: https://travis-ci.org/xadhoom/chronos_test
Repo: https://github.com/xadhoom/chronos_test

Seems that it a travis issue? but really cannot understand where/why.
With other pure erlang libraries this is not happening.

**Comment by lehoff** [comment]
Thanks for the info - I will look into it and see what I can do.
The gproc application thing might be an oversight on my part, but I think it ought to start when you start the chronos application - I will double check that.

**Comment by lehoff** [comment]
When I start `chronos` using `application:start(chronos)` in the Erlang shell gproc is automatically started, so this might be an Elixir thing.

In my mix.exs experiment I tried this:
```
  defp deps do
    [{:chronos, git: "https://github.com/lehoff/chronos.git", tag: "0.1.3", manager: :make}]
  end
``` 
That does _not_ fetch the `gproc` dependency, so either mix has an issue with erlang.mk or I don't know how to use it.

Anyway, I have read the erlang.mk manual and I can generate an rebar.config file from my erlang.mk file without any hassle. So I have done that in 0.1.4 and when you use that in mix.exs it will fetch the `gproc` dependency of `chronos` just fine.

**Comment by xadhoom** [comment]
Confirmed, using the 0.1.4 release makes it work correctly.

thanks!

**Comment by lehoff** [comment]
I have received a PR which switches to rebar3, so this is now fully resolved.
